### ISSUE TITLE
Should the playbook be split into multiple .md files?

### ISSUE THREAD

**Issue by tomdxw** [dxw/playbook#10]
At the moment it's hard to see what top-level sections exist, and it's kind of hard to navigate the document.

If one big page is desirable, there are Markdown implementations which support includes and would thus generate one big HTML page.

We could replace the contents of playbook.md with the following, and split all the content out into smaller files:

```
- [Purpose](purpose.md)
- [Working at dxw](working-at-dxw.md)
- [Build](build.md)
- [Products](products.md)
- [Tickets](tickets.md)
- [Sales](sales.md)
- [Recruitment](recruitment.md)
- [Operations](operations.md)
- [Sharing](sharing.md)
```

**Comment by harry-m** [comment]
Negative - ultimate plan is to host an HTML version. I need to add a section to the readme about this, but haven't yet. In the meantime:

```
cd build
bundle
./compile
open playbook.html
```

This includes an automagically generated table of contents for easier navigation.

**Comment by harry-m** [comment]
(feedback v welcome)

**Comment by tomdxw** [comment]
> ultimate plan is to host an HTML version

A bit like this? http://dxw.github.io/playbook/

```
cd build
bundle install --path=vendor/bundle
bundle exec ./compile
cp playbook.html ../index.html
git checkout --orphan gh-pages
git add ../index.html
git commit -m 'Commit index.html'
git push -f origin gh-pages
```

**Comment by harry-m** [comment]
Yes :D

Can we point DNS at that?

**Comment by tomdxw** [comment]
We should be able to:

https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages/

**Comment by onishiweb** [comment]
@tomdxw @harry-m is there an action from this? Or should we close the issue and create one for setting up a custom domain for the playbook?

**Comment by harry-m** [comment]
I think we can leave this open with the DNS/special branch as the action.

**Comment by harry-m** [comment]
Added #41 to cover this work, as the title of this issue is no longer relevant.
