### ISSUE TITLE
Update reference to former staff

### ISSUE THREAD

**Issue by yndajas** [dxw/playbook#1009]
At [/working-here/getting-things-you-need/claiming-expenses](https://playbook.dxw.com/working-here/getting-things-you-need/claiming-expenses), it tells you to talk to Vanessa if you don't have receipts

**Comment by jacksonj04** [comment]
Where we have named members of staff, is it worth centralising the names in one file as variables and then using `{{role}}` in the templates?

**Comment by snim2** [comment]
> Where we have named members of staff, is it worth centralising the names in one file as variables and then using `{{role}}` in the templates?

I like this idea, but I'm not sure how people who use the CMS/admin interface would make use of it?
