### ISSUE TITLE
Integrate Standard linting into CI

### ISSUE THREAD

**Issue by yndajas** [dxw/playbook#1031]
#984 introduced [JavaScript Standard Style](https://standardjs.com) to the Playbook via a package. This enables linting of JavaScript files to ensure they conform to standard style conventions. If using the companion VSCode plugin or something similar, you can also set up automatic fixing when saving

Before #984, there were no JavaScript files in the repo, but it would be good to integrate Standard linting into the CI pipeline to provide assurance that all future JavaScript code (whether related to search or anything new) is conformant before being merged into `main`

**Comment by snim2** [comment]
@yndajas Do you get warnings in the current `main`?

```shell
standard: Use JavaScript Standard Style (https://standardjs.com)
  .../playbook/src/assets/js/search.js:21:19: 'elasticlunr' is not defined. (no-undef)
  .../playbook/src/assets/js/search.js:26:28: 'lunr' is not defined. (no-undef)
```

**Comment by yndajas** [comment]
I do see those warnings in VSCode - I wonder if it's because we're including `elasticlunr` via a script tag rather than an `import` statement. I'm not sure how we get `lunr` - it's set within `elasticlunr.min.js` but doesn't appear to be exported

Any ideas?

**Comment by yndajas** [comment]
We could try installing via npm instead: https://github.com/weixsong/elasticlunr.js#7-use-elasticlunr-in-nodejs. Still not sure if that would resolve the undefined `lunr` though. We could always disable the warning on a per-line basis before integrating Standard into the CI pipeline

**Comment by lookupdaily** [comment]
Hello. Have opened two PRs related to this, one for resolving these standard errors and one for integrating Standard into the pipeline. 

Have resolved the import error by adding a JavaScript compiler (babel) and webpack - which allows us to use file level imports - but let me know if you think this approach is not suitable.

**PRs**
#1082 
#1083 - linting check will fail until we resolve the first but just have this open for reference
