### ISSUE TITLE
Investigate #-based redirects

### ISSUE THREAD

**Issue by yndajas** [dxw/playbook#1032]
## Problem

In restructuring user research pages, @johnwaterworth sought to redirect from URLs with hash fragments, such as `/guides/how-we-do-user-research#how-we-protect-participant-privacy` or `/user-research/how-we-do-user-research#how-we-protect-participant-privacy`. Given that [JekyllRedirectFrom](https://github.com/jekyll/jekyll-redirect-from) works by creating a HTML file for each URL you want to redirect from (within which is a meta tag that tells the browser to redirect), and `#` is not a valid filename character, it doesn't seem capable of supporting this feature

This issue stems from the shift in #973 from 90+% of content existing on a single page to having many sections each with many pages. Before we relied heavily on hash fragments to direct people within a huge single page, so with the restructure we have a lot of external hash-reliant dead links. The examples from John suggest we may also want redirects from sections within pages from the old guides section, as well as from sections within pages in the new structure

## Solutions

We could do one of the following:
- add code to the 404 page that looks at `window.location.pathname` and `window.location.hash`, looks up some (JSON?) redirect table for a match and redirects if one is found
- manually create the redirect from pages (probably as HTML files, rather than Markdown), and within them include JavaScript to redirect based on hash fragments

While changes to redirects would hopefully be small and infrequent, both of these solutions feel a little too reliant on developer maintenence. Is there anything we can do with Netlify CMS to allow edits to a JSON file, so that we can enable anyone to easily open PRs to maintain redirects?

**Comment by johnwaterworth** [comment]
To understand why this is needed, search for "playbook.dxw.com" in Slack. You'll see lots of messages where someone has asked for help and someone else has responded with a link to the Playbook, that includes a #fragment. Without the redirects, anyone finding those helpful responses in future won't be able to easily follow the links.

**Comment by adamhughes86** [comment]
I've put in a PR for a small fix for this. Not sure if it covers off all situations but it takes the hash before the redirect happens and applies it to the redirect url it's about to use. I think it should improve it

@yndajas - I've added you to the PR as it looks like you've been working on this a lot but let me know if that's wrong

**Comment by adamhughes86** [comment]
@snim2 - for reference ^

**Comment by yndajas** [comment]
@johnwaterworth do you think this covers the scenarios you were thinking of?

Essentially, this will cover: `old_page#a_hash_fragment` to `new_page#a_hash_fragment`. The hash fragment - and therefore the page (sub)heading - would need to be the same in both the old and new page

It won't allow you to do a more custom redirect e.g.:
- `old_page#hash_fragment_one` -> `new_page_one`
- `old_page#hash_fragment_two` -> `new_page_two`

I think the PRs you opened that brought this issue up were trying to do some of that, i.e. you were breaking up what would have been one page into multiple pages, then trying to redirect multiple old links for the same page that contained different hash fragments to multiple smaller new pages, based on their hash fragments

Hope that's clear enough - this is complicated to explain!
