### ISSUE TITLE
There's nothing about the Gourd in the playbook

### ISSUE THREAD

**Issue by duncanjbrown** [dxw/playbook#108]
The Gourd is unique to dxw and it's not explained in writing anywhere. Ought we to have a playbook section about it?

**Comment by CristinaRO** [comment]
I asked about this at the retro, and the conclusion was that this information is better suited to a Bikeshed post, which someone will write.

**Comment by CristinaRO** [comment]
I've created a card in the Fridays Reloaded Trello, putting this issue to rest.
