### ISSUE TITLE
We need a clear steer on what repos can be public

### ISSUE THREAD

**Issue by dgmstuart** [dxw/playbook#12]
See slack conversation: https://dxw.slack.com/archives/devlopers/p1447842651000002

As I understand it, repos which aren't to do with client work should be public unless there's a good reason to have them private (and even some client work should be public if the client agrees). 

We need some clear guidelines in the playbook so that these decisions aren't slowed down by needing to get a ruling from @harry-m.

These should cover:
- What sort of thing can definitely be public
- Reasons/criteria for things needing to be private
- (in a section about kickoff?) When we should ask/encourage clients to make the projects we build for them open source.

**Comment by lawrence-forooghian** [comment]
We agreed that we should move this conversation to https://github.com/dxw/tech-team-rfcs – I'm closing this issue and I'm writing an RFC.
