### ISSUE TITLE
Change references to "dxw" to "dxw digital"

### ISSUE THREAD

**Issue by leedxw** [dxw/playbook#141]
Please change the playbook to note that it is for "dxw digital", since the nature of their work means that "dxw cyber" has a number of different working practices and constraints.

**Comment by CristinaRO** [comment]
Hi @leedxw , are you content with the amount of differentiation that now exists, for example http://playbook.dxw.com/#/?id=openness-and-confidentiality-dxw-cyber ? And if not, could you point us to the places that still need disambiguation?

**Comment by leedxw** [comment]
This is fine, and now reflects the different approach to confidentiality and openness that I was concerned about.

**Comment by CristinaRO** [comment]
Thank you! OK to close the issue?
