### ISSUE TITLE
Tickets on projects in sprints

### ISSUE THREAD

**Issue by onishiweb** [dxw/playbook#18]
Have discussed this with @imagecircus, it would be good to have a guide in place that when a developer is sprinting on a project, they also get assigned the tickets for the project so they can integrate that with the current work in the sprint. We've had issues where 2 developers have been sprinting on a project while another did a ticket which conflicted with the work being done on the sprint, so developers on the sprint will be much more aware of how to deal with the tickets that come in at that point.

**Comment by harry-m** [comment]
This is a really excellent suggestion and I'm sad to have lost track of it! I think it's definitely a good thing for ops and DMs to keep in mind when assigning tickets.

**Comment by imagecircus** [comment]
@harry-m This was the motivation for making the screen that displays who's sprinting on what to help Ops know who to assign tickets to.

**Comment by harry-m** [comment]
:thumbsup:
