### ISSUE TITLE
Security checklist

### ISSUE THREAD

**Issue by mallorydxw** [dxw/playbook#32]
We need a checklist to run through before we deploy a site. (And we should check for compliance regularly - maybe as something we do at the start of each sprint - or as part of the sprint retro?).
- All plugins must have been inspected by dxw, and they must be "no issues found" or "use with caution" (except in very special circumstances)
- When creating a new user, passwords less than 10 (12?) characters should be rejected (shouldn't need to check this with WP sites as dxw-extras does this)
- When creating a new user, passwords should be checked against a word list (?)
- Login forms should not reveal whether a user account exists or not (shouldn't need to check this with WP sites as dxw-extras does this - but maybe we should check anyway)

We should also make sure all WP developers understand that plugins need inspecting.

**Comment by harry-m** [comment]
Good idea. We should perhaps start a guide for this, and think about which things could be checked automagically.

The inspections one is definitely something we should do, and it's something I've discussed a bit with @dgmstuart - converting Mongoose into a tool for Ops to use.

The new user password length should be enforced by extras across the platform but there's definitely no harm in checking that every so often. We could definitely set up a GhostInspector test against one of the smoke test sites to do that.

Extras should be checking passwords against the list on new user creation as well - have you seen something that suggests that it isn't? Possible I guess that we are only checking password changes and not user creation?

The login forms thing we should be able to test for on a smoketest site as well.

**Comment by CristinaRO** [comment]
@mallorydxw Is this issue still something to be worked on? Feel free to tag people by name if no one responded to the "help wanted" label. :)

**Comment by mallorydxw** [comment]
@CristinaRO Yeah, we still need something like this. I don't know who to tag though.

**Comment by erbridge** [comment]
@RobjS Think you could add this to the GovPress team backlog?

**Comment by RobjS** [comment]
I think most of these things are covered on WP sites by dxw-extras (which may not have been the case when Mallory originally opened the issue):

- it enforces min password length of 10 characters
- it rejects any passwords that are found on our banned list: https://git.govpress.com/ops/chef-repo/-/blob/master/cookbooks/websites/files/default/banned_passwords.txt
- it doesn't reveal on failed login attempts (or password recovery requests) whether the user account exists

I've added a card to the GovPress backlog for agreeing a general set of actions we should do at the start of any sprint: https://trello.com/c/kZYYv9Qd/75-agree-a-set-of-actions-that-should-occur-at-the-start-of-any-client-sprint.

My reading of the intention behind this was that we should have a checklist like this for all that is applied across all our projects, not just the GovPress ones.

**Comment by erbridge** [comment]
This is old enough, that I think it's "ded". Closing.
