### ISSUE TITLE
Data protection section signposts to Harry

### ISSUE THREAD

**Issue by CristinaRO** [dxw/playbook#345]
From https://playbook.dxw.com/#/?id=data-protection:

"If you have any questions about data protection, talk to Harry."

Should it signpost to a role or roles rather than a specific individual?

**Comment by erbridge** [comment]
Instead of Harry, who should it be? Head of Technical Operations?

**Comment by johnwaterworth** [comment]
I believe it Poss is our Data Protection Officer (DPO). But worth checking with him.
