### ISSUE TITLE
AXE audit found 132 accessibility issues

### ISSUE THREAD

**Issue by calumryan** [dxw/playbook#350]
Using the AXE browser extension the playbook has 132 accessibility issues listed here.

<img width="318" alt="list of accessibility issues on AXE" src="https://user-images.githubusercontent.com/2226904/82880280-19e96d00-9f36-11ea-9c5e-927671b98f79.png">

In addition the guides menu button isn't accessible without a focus state or way to toggle beyond hovering.

**Comment by calumryan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Resolve accessiblity issues on Playbook](https://trello.com/c/bWWTHrwS/50-resolve-accessiblity-issues-on-playbook)

**Comment by CristinaRO** [comment]
Hopefully fixed in #365 , but we should re-run the accessibility checks to verify.

**Comment by erbridge** [comment]
Even better if we ran them as part of CI (we could use https://github.com/nickcolley/jest-axe).

**Comment by calumryan** [comment]
Thanks, all automated tests from above passed
