### ISSUE TITLE
Lateness link doesn't work

### ISSUE THREAD

**Issue by frabcus** [dxw/playbook#37]
The word "late" in the sentence "If you miss the stand-up, then you are late." links to "#lateness" which doesn't exist.

**Comment by harry-m** [comment]
I seem to have not written it yet! But when I do, it'll basically be the same as this: 

![flow chart of lateness](https://cloud.githubusercontent.com/assets/146397/17889652/2a8d4b64-6929-11e6-9bf4-0f4da75570a8.png)

**Comment by CristinaRO** [comment]
The broken link has been fixed. This has existed for more than 2 years without anyone writing anything more about it, so in the spirit of closing things that have been lingering for more than a year, we are closing this.
