### ISSUE TITLE
Support sections need review

### ISSUE THREAD

**Issue by CristinaRO** [dxw/playbook#412]
There are several places in the playbook where we talk about handling support. Some of them need specific changes, others need reviewing for redundancy or contradictions.
  * Team changes and handovers guide
    https://playbook.dxw.com/guides/team-changes-and-handovers.html
    The Rota spreadsheet is not the source of truth, it should mention OpsGenie as the primary source
  * Support helpdesk section
    https://playbook.dxw.com/#support-helpdesk
  * Support and on call guide
        https://playbook.dxw.com/guides/support-and-on-call#being-on-first-line-support

**Comment by erbridge** [comment]
I do wonder if we should strip it out and rewrite it from the current context.

**Comment by erbridge** [comment]
https://bikeshed.dxw.com/2020/12/11/changes-to-the-developer-support-rota/ is relevant to the team changes guide.
