### ISSUE TITLE
Where did the section on story writing go to?

### ISSUE THREAD

**Issue by conatus** [dxw/playbook#432]
Hey all,

Long time listener, first time caller.

At [Common Knowledge](https://commonknowledge.coop/) we've been consistently fans of the dxw playbook. We massively respect your commitment to openness. Thanks for maintaining it and opening it up in the first place!

There used to be a section in the playbook that described the process of writing user stories that I really enjoyed and often linked people to. It also recommended _User Stories Applied: For Agile Software Development_, which I actually bought off the back of. One neat thing it talked about was how to invert the user story when giving the "card" a title, which was one of th best descriptions of this process I've read, so referred to it often.

I can't seem to find it in the current version of the playbook. Wondering where, if anywhere, you moved it to? No problem if it has just been deleted. I'll dig through Git.

Thanks again.

**Comment by CristinaRO** [comment]
Hi @conatus ,

Thank you for your kind words about our Playbook! We're always happy to hear it's helped someone else. :D

This is the section in question: https://playbook.dxw.com/#user-stories

**Comment by conatus** [comment]
Thanks @CristinaRO!

That's exactly what I was looking for.

Keep up the good work.
