### ISSUE TITLE
Playbook needs a section on how we install new plugins on WordPress sites

### ISSUE THREAD

**Issue by harry-m** [dxw/playbook#45]
To cover - 
- Stuff that doesn't work on GovPress
- Inspections
- Looking for an existing inspection
- Open source vs not
- auto-wordpress Git section

**Comment by CristinaRO** [comment]
Rather than adding to the playbook, we are now documenting WordPress related tasks in the Support documentation, where we have this section: https://git.govpress.com/ops/docs/blob/master/wordpress/plugins/adding-a-new-plugin.md
