### ISSUE TITLE
Advice on deploying is out of date

### ISSUE THREAD

**Issue by dgmstuart** [dxw/playbook#53]
https://github.com/dxw/playbook/blob/master/playbook.md#deploying

the playbook says

> On WordPress projects, we deploy by pushing commits to the testing or production branch on GovPress. Other projects have their own approaches, which are documented in their READMEs.

Apparently that's very old:

> `master` and `stage` were the branches we used until this week. (Now it's going to be `master` and `develop`).

**Comment by Stretch96** [comment]
https://github.com/dxw/playbook/pull/54

**Comment by staceydxw** [comment]
This issue is resolved as all deployment guidance is now in the dev guide https://github.com/dxw/playbook/blob/master/guides/development-workflow.md
