### ISSUE TITLE
Style guide violates style guide (bullet points)

### ISSUE THREAD

**Issue by tomdxw** [dxw/playbook#62]
https://www.gov.uk/guidance/style-guide/a-to-z-of-gov-uk-style#bullet-points-steps

Specifically:

- you always use a lead-in line
- you use lower case at the start of the bullet
- you don’t use more than one sentence per bullet point - use commas, dashes or semicolons to expand on an item

**Comment by staceydxw** [comment]
I'm not sure I understand this? Are you suggesting that we use the GOV.UK style guide for the development guide?

**Comment by tomdxw** [comment]
@staceydxw Sorry for not explaining properly. [Our style guide](https://github.com/dxw/playbook/blob/master/guides/style-guide.md#a-z) says "we also follow the GOV.UK style guide".

The README of this repo says "These documents are maintained by everyone at dxw, and it's important that their quality and tone is consistent." which one can assume means "use the styleguide for everything here".

So yes, everything in this repo needs to conform to the style guide.
