### ISSUE TITLE
Make a guide for creating invoices

### ISSUE THREAD

**Issue by harry-m** [dxw/playbook#66]
Old content:

> Creating an Invoice
> In Xero – click “add a sales invoice”
> 
> There are a bunch of fields – to be filled in as follows:
> 
> Top Row
> 
> To
> The name of the organisation on the PO – may already be on the list. If not, it will be created.
> Date
> The approximate date you expect the invoice to be payable from.
> Due date
> The same date in the next month
> Invoice#
> Don’t change this – it’s automatically generated
> Reference
> This should be a short 2 or 3 descriptive words, followed by “PO < e.g. “NTDA migration (PO NTDA1065)”. You can look the PO number up in Clients & Projects
> Amounts are
> Always leave as “Tax Exclusive”
> Table
> 
> Item
> Always leave blank (we don’t use it)
> Description
> A decent description of what the charge is for. For some fastidious customers it’s best to break this down as per the proposal, with one line per item. Otherwise (and especially if total costs have been discussed previously) use your judgement as to what level to break it down to.
> Qty
> Unless you have a good reason to do otherwise, for fixed price work this should be 1
> For time-and-materials work this should be the number of days of each type of work
> Unit Price
> For fixed price work – the cost of the work (usually from the proposal)
> For time-and-materials work, the day rate in question
> Disc %
> Always 0
> Account
> Almost always one of the 200 accounts (if not, you need to discuss with Harry)
> 200 – Fees (bespoke)
> Any one-off item of agency or development work
> 201 – Fees (recurring)
> Things like reservation fees and certificates. NOT monthly hosting costs – those are dealt with separately by Harry
> 202 – Fees (products)
> Citrulu etc. This is all kind of TBC
> Tax Rate
> Automatically calculated. Don’t mess.
> Products
> Agency
> any custom work, development or content/editorial work
> Hosting
> Anything directly to do with hosting, support and maintenance but not original development work. Includes set up costs, chargeable sysadmin work etc.
> For draft invoices
> 
> “Save” the invoice, do not submit for approval.

**Comment by CristinaRO** [comment]
Closed after talking to Leanne G, who is writing a more update guide already.
