### ISSUE TITLE
Update office accessibility for Leeds

### ISSUE THREAD

**Issue by calumryan** [dxw/playbook#661]
Still references to the Hoxton Square, keep same format but for Leeds office?
https://playbook.dxw.com/guides/office-accessibility.html

**Comment by CristinaRO** [comment]
@calumryan What would be preferable in your view - taking down the page, because we don't have up to date information (might break bookmarks pointing to the link), or replacing it with a placeholder to the tune of "we have not compiled this info yet"?

**Comment by calumryan** [comment]
@CristinaRO preferably keep it with a placeholder including some contact info for who might know for each location (not ideal, but better than nothing).
