### ISSUE TITLE
Add setup instructions for HTML version of the playbook

### ISSUE THREAD

**Issue by onishiweb** [dxw/playbook#8]
Be good to have some quick setup instructions on how to get the HTML version up and running, maybe add a readme to the `/build` directory?

**Comment by harry-m** [comment]
Hah. I moved the main stuff to playbook.md and changed README.md into an actual readme for exactly this reason and then got sidetracked by the style guide :)

Let's add a section.

**Comment by onishiweb** [comment]
@harry-m I'm going to add a section on building the playbook locally (I think I remember how).

@tomdxw what did you do to set up the `gh-pages` branch? I've seen there's only one commit of the index.html on there, do you have a plan for continuing to update the `gh-pages` version?

**Comment by tomdxw** [comment]
@onishiweb Instructions here: https://github.com/dxw/playbook/issues/10#issuecomment-152273205 Presumably we'd want to stick that script on a server somewhere so it can be run on a daily basis, or set up a webhook to run it on push.

**Comment by harry-m** [comment]
Resolved by #41.
