### ISSUE TITLE
Who is responsible for creating Trello cards for tickets, and when?

### ISSUE THREAD

**Issue by RobjS** [dxw/playbook#80]
If a Zendesk ticket requires any changes to a repo, it should be accompanied by a Trello card. This is the only way we can ensure we don't deploy changes that aren't ready for live. 

At what stage in the ticket lifecycle should the Trello ticket be created? As soon as it comes in? Or just once it's been assigned to a developer? Or once that developer has decided code changes are necessary?

**Comment by tahb** [comment]
I'd lean towards the developer making it when they have decided code changes are necessary. 

I imagine making cards straight away might make Trello very noisy in the cases where no code change is required. I come across some tickets that only required investigation which wouldn't have needed a card, is that uncommon in your experience @RobjS?

**Comment by RobjS** [comment]
@tahb I would say the majority of the tickets that get as far as the WordPress devs require some sort of code change, because those that don't are often resolved in triage. But it certainly isn't unusual to get a ticket that just requires investigation or a plugin setting tweak.

I agree that creating cards for all tickets would be messy... but I also wonder if only creating cards once a dev has decided they need to make code changes is a recipe for people just forgetting to create cards, especially if that ticket has been bouncing around for a while before it gets to that stage. Maybe it's just a question of getting into that habit?

**Comment by tomdxw** [comment]
@RobjS Well the developer should be moving the card into the "awaiting code review" column before they ask for a code review. And they should be moving it out of the "reviewed" column and into the "on staging" column. So they should have several opportunities to realise that the card isn't there.

I think we should also stop posting links to GitLab in #wordpress-developers. We should link to the card. The reviewer moves your card into "code review", does the code review, and then moves it into the next appropriate column. That way it's less likely that the reviewer will forget to move the card. And if you forget to create a card, somebody will say "hey, no GitLab links" and you'll probably remember next time.

**Comment by RobjS** [comment]
@tomdxw I like the idea of posting links to trello cards rather than MRs if we need reviews, that'd definitely get us in the right habit. Except it looks like gitlab has been set up in the last couple of days to post new MRs to Slack, so that bit is happening automatically now. I wonder if we could replace that with Slack notifications when a Trello card is moved to "awaiting review"?

**Comment by tomdxw** [comment]
@RobjS I don't know how we'd do that easily. The columns in Trello projects all have different names. There's a Trello "powerup" for Slack, but it asks for quite a lot of permissions.

Maybe for the moment we should just turn off the GitLab integration, and go back to manually posting links (and manually complain at anybody posting links to GitLab), and then figure out how to get Trello working later?

**Comment by tahb** [comment]
We use the Slack with Trello to post to the project channel when a card changes state/column and it is very useful for us and clients.

As WP use the same channel the same approach would also become very very noisy as there's no way (that I know of) to isolate the notifications to be per specific column.

@tomdxw We have a GitLab integration? I missed that, thought the Zendesk integration was the one used.

**Comment by tomdxw** [comment]
> We have a GitLab integration?

Take a look in #wordpress-developers. GitLab posts whenever a MR is created or merged.

>  I missed that, thought the Zendesk integration was the one used.

I think the Zendesk integration is hooked up to #systems.

**Comment by robbiepaul** [comment]
@RobjS @tomdxw @tahb there's a Zapier integration for sending a Slack message when a card moves to a list: https://zapier.com/app/editor/template/11679 - not sure if it's something we can use?

**Comment by tahb** [comment]
@tomdxw Ah, I thought you were still on the subject of Trello integrations, not to worry.

@robbiepaul That sounds like the same as the official Slack & Trello integration. I don't think you can limit it to a particular list?

Aside from which integration we use, do you all feel we should continue to centralise them in #wordpress-developers as opposed to the individual project channels?

**Comment by robbiepaul** [comment]
@tahb I just checked. You can specify a list 
![screen shot 2017-01-24 at 16 23 54](https://cloud.githubusercontent.com/assets/2804149/22256115/a654f46c-e251-11e6-8fe9-ee15cc417148.png)

**Comment by robbiepaul** [comment]
Actually, just checked their pricing - doesn't seem worth it.

I think reporting to #wordpress-developers is better than the individual project

**Comment by RobjS** [comment]
I think the posting to #wordpress-developers is generally working well. The one hesitation I have is that it can make using that channel for actual discussion a bit tough. There's usually a pretty steady flow of MRs, so it's easy for conversations/questions to get lost. But maybe that's just something we need to all be aware of.

**Comment by tahb** [comment]
Back to your most recent question on the issue @RobjS:

> I also wonder if only creating cards once a dev has decided they need to make code changes is a recipe for people just forgetting to create cards, especially if that ticket has been bouncing around for a while before it gets to that stage. Maybe it's just a question of getting into the habit?

I think that's right, there needs to be a manual step made by the developer at some point. The Zendesk function/plugin that means you can create any ticket into a Trello card with minimal effort should help automate this completely.

**Comment by harry-m** [comment]
What needs to happen next here?

**Comment by tahb** [comment]
Closing as the conversation has now petered out. I think we've learnt that tickets should not automatically become cards but when development is deemed necessary then they are done so by the developers at that point.
