### ISSUE TITLE
Review playbook ticket process in light of new workflow and write down oncall & support dev responsibilities

### ISSUE THREAD

**Issue by harry-m** [dxw/playbook#83]
https://bikeshed.dxw.com/2017/01/27/how-we-do-support-and-new-ticket-workflow/

**Comment by CristinaRO** [comment]
The process has changed again since then, and we have reviewed the playbook and created new guidance for people on support in the ops docs repo, which is now the first source for this info: https://git.govpress.com/ops/docs
