### ISSUE TITLE
We don't have a policy for which teams can access github projects

### ISSUE THREAD

**Issue by dgmstuart** [dxw/playbook#9]
Govsite and UKTI have all dxw staff having commit access
TVH has a specific team
WP devs exists as a team and I've used that for DH Intranet.

I don't care what the policy is, but we need one written down, with a rationale.

**Comment by dgmstuart** [comment]
Also who should have admin access?

**Comment by harry-m** [comment]
I think @zeeraw has just fixed the owners team issue.

More broadly - yes, we need this. My next big job is rewriting and migrating the ISMS documentation into the playbook, which will cover this.

**Comment by CristinaRO** [comment]
Closing (info in #tech-team Slack from @rjw1 )
