### ISSUE TITLE
Revert sidebar to cream

### ISSUE THREAD

**Issue by yndajas** [dxw/playbook#978]
This was changed in #973 as part of work that split the sidebar in two, but in the end the sidebar ended up as a single column. We might want to revert to cream to keep the old design, which had more visual differentiation from the top nav (and more of a consistently quadrilateral colour block design, whereas now we have one six-sided L shape blue block and two quadrilaterals) 

See: https://github.com/dxw/playbook/pull/973#discussion_r988884531

**Comment by erbridge** [comment]
Note that we override that colour on mobile, so there are two places to edit if changing the colours.

**Comment by yndajas** [comment]
> Note that we override that colour on mobile, so there are two places to edit if changing the colours.

Default/mobile: https://github.com/dxw/playbook/blob/main/src/_sass/_related.scss#L8
Large screens: https://github.com/dxw/playbook/blob/main/src/_sass/_related.scss#L50
